name: ci
on:
  pull_request:
    paths:
      - .github/workflows/pytest.yaml
      - torchscript_lavis/**
      - tests/**
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  release:
    types: [published]

jobs:
  ci:
    name: ci
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.12"]
        poetry-version: ["1.5.1"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install
        run: poetry install
      - name: test
        run: poetry run pytest -v --cov=./torchscript_lavis --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: pytest # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: models
          path: |
            *.pt
          retention-days: 1